### ISSUE TITLE
3/4 happy pictures get classified as angry

### ISSUE THREAD

**Issue by shadiakiki1986** [enricodata/emotion-faces#1]
I uploaded 4 happy pictures, and 3 of them got "angry" albeit with probabilities around 0.5. Perhaps your model needs more training? I used the bitly link from the blog https://www.enricodata.com/post/how-to-deploy-a-deep-learning-model-with-binder-and-voila/

**Comment by enricodata** [comment]
with more images for training probably the model would give more accurate results.
However the purpose of this application was for me just to learn how do it
